name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6 # ou a versão que você estiver usando

      - name: Configurar credenciais AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: echo "Credenciais configuradas"

      - name: Inicializar Terraform
        working-directory: infra
        run: terraform init

      - name: Validar configuração
        working-directory: infra
        run: terraform validate

      - name: Executar plano
        working-directory: infra
        run: terraform plan
